---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  roles:
    - role: nfs/server
    - role: k3s/master
    - role: k3s_information

- hosts: node
  become: yes
  roles:
    - role: nfs/client
    - role: k3s/node

- hosts: storage
  become: yes
  roles:
    - role: storages
